name: Problem Report
description: please report any technical issue with this home assistant integration - please note this is not a official Ovum repository or service
labels: bug
body:
  - type: dropdown
    id: system
    attributes:
      label: With which version of the integration you have an issue?
      multiple: false
      options:
        - "Ovum Mira control unit"
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Add a description
      placeholder: "Please provide details about your issue - in the best case a short step by step instruction how to reproduce the issue."
  - type: textarea
    id: logs
    attributes:
      label: Add your DEBUG log output
      placeholder: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell